const players = [

/* ================= ICON PLAYERS ================= */

{sr:1,name:"ARJUN GORAIN",cat:"ICON"},
{sr:4,name:"TRIDIP KARMAKAR",cat:"ICON"},
{sr:7,name:"AFJAL ANSARY",cat:"ICON"},
{sr:10,name:"NIMAI MAHATHA",cat:"ICON"},
{sr:48,name:"RAJESH CHATTERJEE (RAJU)",cat:"ICON"},
{sr:51,name:"SUBHADIP CHATTERJEE",cat:"ICON"},
{sr:65,name:"MOHIT MOHTA",cat:"ICON"},
{sr:91,name:"PORAN BAURI",cat:"ICON"},
{sr:139,name:"SATYASADHAN RAJAK (INDRA)",cat:"ICON"},
{sr:151,name:"PRAKASH PRASAD",cat:"ICON"},
{sr:162,name:"MD IRFAN",cat:"ICON"},
{sr:163,name:"SUMIT KARMAKAR",cat:"ICON"},
{sr:189,name:"SANTOSH RAM",cat:"ICON"},
{sr:205,name:"BIJOY SAHANI",cat:"ICON"},
{sr:233,name:"BIKASH SHARMA (CHOTIYA)",cat:"ICON"},
{sr:259,name:"INDRANIL SINGHA DEO (MANA)",cat:"ICON"},
{sr:261,name:"PRAVIN SINGH",cat:"ICON"},
{sr:290,name:"ASHRAFUL ANSARY",cat:"ICON"},

/* ================= U23 PLAYERS ================= */

{sr:15,name:"MD AJAZ",cat:"U23"},
{sr:18,name:"SOURAV (SANTY)",cat:"U23"},
{sr:21,name:"BITTU PANDEY",cat:"U23"},
{sr:27,name:"SEKH ABU SUFYAN",cat:"U23"},
{sr:32,name:"ANURAG TRIPATHY (BHATI)",cat:"U23"},
{sr:34,name:"MD TOUHID ALAM",cat:"U23"},
{sr:37,name:"DHIREN CHATTERJEE (DHIRU)",cat:"U23"},
{sr:38,name:"SUSANTA KUMBHAKAR",cat:"U23"},
{sr:41,name:"ABHIJIT MAITY",cat:"U23"},
{sr:42,name:"AYAN GHOSH",cat:"U23"},
{sr:43,name:"VISHAL RAJ",cat:"U23"},
{sr:46,name:"TAPAJOTI BAURI (TUFAN)",cat:"U23"},
{sr:49,name:"DEEP GOSWAMI (DEB)",cat:"U23"},
{sr:53,name:"ADARSHA GANGULI",cat:"U23"},
{sr:62,name:"HARADHAN BAURI",cat:"U23"},
{sr:63,name:"MD ARBAZ (BABA)",cat:"U23"},
{sr:74,name:"PRALAY SINGHA DEO (DHONA)",cat:"U23"},
{sr:79,name:"KRISH RAY",cat:"U23"},
{sr:81,name:"PARTHA MAHATO",cat:"U23"},
{sr:83,name:"RONIK CHATTERJEE",cat:"U23"},
{sr:84,name:"AKASH KUIRI",cat:"U23"},
{sr:92,name:"SUVADIP MAJEE (SUBHA)",cat:"U23"},
{sr:93,name:"RAJA BHUINA",cat:"U23"},
{sr:101,name:"AMRIT CHATTERJEE",cat:"U23"},
{sr:103,name:"RATAN BAURI",cat:"U23"},
{sr:108,name:"SIBAM SANTIKARY",cat:"U23"},
{sr:115,name:"WARISH AHMED",cat:"U23"},
{sr:123,name:"SUDIP MAJEE",cat:"U23"},
{sr:125,name:"DILKHUS ANSARI",cat:"U23"},
{sr:127,name:"ARKA MUKHERJEE",cat:"U23"},
{sr:128,name:"DILKHUSH RAJAK",cat:"U23"},
{sr:130,name:"CHANDRANSHU MAHATO",cat:"U23"},
{sr:132,name:"INDRAJIT MAHATO (PAPAI)",cat:"U23"},
{sr:133,name:"DWIPAN BANERJEE",cat:"U23"},
{sr:134,name:"BHAGBAT PAUL",cat:"U23"},
{sr:135,name:"ROHAN RAO",cat:"U23"},
{sr:137,name:"ROKI RAJAK",cat:"U23"},
{sr:138,name:"RUDRA MUKHERJEE (LABUSEN)",cat:"U23"},
{sr:141,name:"PINTU RAJAK",cat:"U23"},
{sr:147,name:"SUJAY KARMAKAR",cat:"U23"},
{sr:149,name:"RAHUL GOSWAMI",cat:"U23"},
{sr:150,name:"SERAFAT ANSARY",cat:"U23"},
{sr:153,name:"PRASHANT KUMAR (ANUPAM)",cat:"U23"},
{sr:156,name:"MAHABIR SHUKLA (HARDIK)",cat:"U23"},
{sr:160,name:"MOHAMMED THOHEED (MUNNA)",cat:"U23"},
{sr:168,name:"PANKAJ MAHATO",cat:"U23"},
{sr:169,name:"SWAPAN MAHATO (SAYAN)",cat:"U23"},
{sr:175,name:"SHUBHAM PODDAR",cat:"U23"},
{sr:177,name:"DINESH KARMAKAR",cat:"U23"},
{sr:178,name:"SABBIR ALAM",cat:"U23"},
{sr:183,name:"BABU SWARNKAR (KHEDU)",cat:"U23"},
{sr:194,name:"AKASH KUMAR DAS",cat:"U23"},
{sr:195,name:"BISHAL DUBEY",cat:"U23"},
{sr:197,name:"DEBASHIS MAJHI",cat:"U23"},
{sr:198,name:"SHUBHAJIT SEN",cat:"U23"},
{sr:207,name:"SOURAV GORAIN",cat:"U23"},
{sr:209,name:"MUKESH MAJEE",cat:"U23"},
{sr:210,name:"SUMIT KUMAR",cat:"U23"},
{sr:214,name:"ASHUTOSH KUMAR SINGH",cat:"U23"},
{sr:222,name:"GOURAB KAR",cat:"U23"},
{sr:224,name:"BISWAJIT ORANG",cat:"U23"},
{sr:236,name:"SOUMIK GHOSH",cat:"U23"},
{sr:238,name:"GOURAV PANDEY",cat:"U23"},
{sr:241,name:"SK RIYAZ",cat:"U23"},
{sr:242,name:"DEEP MUKHERJEE",cat:"U23"},
{sr:244,name:"ROUNAK PANDEY",cat:"U23"},
{sr:251,name:"RAHUL GANGULI",cat:"U23"},
{sr:253,name:"FARHAN ANSARY",cat:"U23"},
{sr:264,name:"KUNDAN DUBEY",cat:"U23"},
{sr:269,name:"TAPASH PAUL",cat:"U23"},
{sr:272,name:"SANDIPAN BANERJEE",cat:"U23"},
{sr:274,name:"SANJOY SEN",cat:"U23"},
{sr:280,name:"AVIJIT ROY",cat:"U23"},
{sr:284,name:"KOUSHIK MAHATO",cat:"U23"},
{sr:288,name:"ANIRBAN KUNDU",cat:"U23"},
{sr:294,name:"PREM BARAL",cat:"U23"},
{sr:300,name:"TAMAL CHAKRABORTY",cat:"U23"},
{sr:309,name:"SAYAN SENAPATI",cat:"U23"},
{sr:313,name:"SUBHA SHILL",cat:"U23"},
{sr:314,name:"BIKRAM MAHATO",cat:"U23"},
{sr:315,name:"AYUSH AGARWAL",cat:"U23"},
{sr:320,name:"GOPAL DEY",cat:"U23"},
/* ================= ABOVE 40 PLAYERS ================= */

{sr:12,name:"PRASANTA KARMAKAR",cat:"ABOVE 40"},
{sr:20,name:"AJITESH GANGOPADHYAY",cat:"ABOVE 40"},
{sr:31,name:"MANAS CHAKRABORTY",cat:"ABOVE 40"},
{sr:36,name:"GOBINDA BAURI",cat:"ABOVE 40"},
{sr:39,name:"MD ANIS",cat:"ABOVE 40"},
{sr:47,name:"CHAITANYA DEV BOURI",cat:"ABOVE 40"},
{sr:57,name:"TARUN KUMAR CHOUDHURY",cat:"ABOVE 40"},
{sr:69,name:"SOURAV DEY",cat:"ABOVE 40"},
{sr:78,name:"SANJU DHABALBABU",cat:"ABOVE 40"},
{sr:90,name:"PRESENJIT GOSWAMI",cat:"ABOVE 40"},
{sr:100,name:"DEBDAT GANGULY (PAPPU)",cat:"ABOVE 40"},
{sr:124,name:"KAJAL MAHATO",cat:"ABOVE 40"},
{sr:145,name:"SRIKANTA MAHATO",cat:"ABOVE 40"},
{sr:148,name:"AMAR JAISWAL (LALLA)",cat:"ABOVE 40"},
{sr:155,name:"SANTANU BANERJEE",cat:"ABOVE 40"},
{sr:172,name:"AMZAD KHAN",cat:"ABOVE 40"},
{sr:181,name:"BISWAJIT DEY",cat:"ABOVE 40"},
{sr:187,name:"MUKENDAR SINGH",cat:"ABOVE 40"},
{sr:270,name:"SK AMANUL",cat:"ABOVE 40"},
{sr:271,name:"SAJID SAHA",cat:"ABOVE 40"},
{sr:296,name:"BAPI RAJAK",cat:"ABOVE 40"},
{sr:322,name:"BIKASH KARMAKAR",cat:"ABOVE 40"},

/* ================= NORMAL CATEGORY PLAYERS ================= */

{sr:2,name:"KAMAL SHAW",cat:"NORMAL"},
{sr:3,name:"SOURAV MAHATO",cat:"NORMAL"},
{sr:5,name:"BIPUL SINGH SARDAR",cat:"NORMAL"},
{sr:6,name:"SARFARAJ SEIKH",cat:"NORMAL"},
{sr:8,name:"RAHUL CHANDRA MAHATO",cat:"NORMAL"},
{sr:9,name:"SANJOY MAHATO",cat:"NORMAL"},
{sr:11,name:"PRASENJIT BANERJEE",cat:"NORMAL"},
{sr:13,name:"SAMBHU BAURI",cat:"NORMAL"},
{sr:14,name:"TAPAS DEB (MITHUN)",cat:"NORMAL"},
{sr:16,name:"ARUP KUMAR SENAPATI",cat:"NORMAL"},
{sr:17,name:"MASUM ANSARI",cat:"NORMAL"},
{sr:19,name:"GANESH SUKLA",cat:"NORMAL"},
{sr:22,name:"BIKASH MAHATO",cat:"NORMAL"},
{sr:23,name:"SOURAB KARMAKAR (BALI)",cat:"NORMAL"},
{sr:24,name:"BISHNUPADA DUTTA",cat:"NORMAL"},
{sr:25,name:"SANU PARAMANIK",cat:"NORMAL"},
{sr:26,name:"DEBASIS BANERJEE",cat:"NORMAL"},
{sr:28,name:"NAYAN SARAK",cat:"NORMAL"},
{sr:29,name:"UTTAM TUDU",cat:"NORMAL"},
{sr:30,name:"SUBHAM RAY",cat:"NORMAL"},
{sr:33,name:"KOUSHIK MANDAL",cat:"NORMAL"},
{sr:35,name:"RANJIT GOPE (JHALI)",cat:"NORMAL"},
{sr:40,name:"RAJIB RAKSHIT (RAJA)",cat:"NORMAL"},
{sr:44,name:"SWARUP GOSWAMI",cat:"NORMAL"},
{sr:45,name:"PALLAB MAHATO",cat:"NORMAL"},
{sr:50,name:"RAHUL ROY (HITMAN)",cat:"NORMAL"},
{sr:52,name:"RON CHAKRABORTY",cat:"NORMAL"},
{sr:54,name:"MAHARAM ANSARI",cat:"NORMAL"},
{sr:55,name:"SOMNATH MUKHERJEE",cat:"NORMAL"},
{sr:56,name:"JHULAN ROY",cat:"NORMAL"},
{sr:58,name:"PINTU KAIBARTA",cat:"NORMAL"},
{sr:59,name:"SACHIN BAURI",cat:"NORMAL"},
{sr:60,name:"SATYAJIT MAHATO",cat:"NORMAL"},
{sr:61,name:"SURAJ BANERJEE (MONAI)",cat:"NORMAL"},
{sr:64,name:"SOUMYADIPTA CHATTERJEE",cat:"NORMAL"},
{sr:66,name:"SAIKAT ROY",cat:"NORMAL"},
{sr:67,name:"GOURAV MUKHERJEE",cat:"NORMAL"},
{sr:68,name:"SARNENDU MAHATO",cat:"NORMAL"},
{sr:70,name:"BISWANATH SEN (SONU)",cat:"NORMAL"},
{sr:71,name:"AVIJIT KARMAKAR",cat:"NORMAL"},
{sr:72,name:"NIZAMUDDIN ANSARI (GAJU)",cat:"NORMAL"},
{sr:73,name:"AMIYA MAHATO",cat:"NORMAL"},
{sr:75,name:"SOMNATH GORAI",cat:"NORMAL"},
{sr:76,name:"BISWAJIT ROY",cat:"NORMAL"},
{sr:77,name:"PROBIR CHAND",cat:"NORMAL"},
{sr:80,name:"UJJWAL MUKHERJEE",cat:"NORMAL"},
{sr:82,name:"AMRIT DHIBAR",cat:"NORMAL"},
{sr:85,name:"RUPESH SINGH (RUPA)",cat:"NORMAL"},
{sr:86,name:"SURAJ RAJAK",cat:"NORMAL"},
{sr:87,name:"NITAI MAHATO",cat:"NORMAL"},
{sr:88,name:"PARTHA SARATHI MAHATO",cat:"NORMAL"},
{sr:89,name:"BALARAM BAURI",cat:"NORMAL"},
{sr:94,name:"AMIT KHEDIA (MICKEY)",cat:"NORMAL"},
{sr:95,name:"BHASKAR BAURI",cat:"NORMAL"},
{sr:96,name:"BIMAL MAHATO",cat:"NORMAL"},
{sr:97,name:"SOURAV LOHAR",cat:"NORMAL"},
{sr:98,name:"SUBHAJIT CHATTERJEE",cat:"NORMAL"},
{sr:99,name:"TAPAS MAHATO",cat:"NORMAL"},

/* ---- CONTINUED ---- */

/* Remaining NORMAL players from 102 to 325 */

{sr:102,name:"ASWINI BOURI",cat:"NORMAL"},
{sr:104,name:"AJAY MONDAL",cat:"NORMAL"},
{sr:105,name:"ACHINTA BAURI (ABD)",cat:"NORMAL"},
{sr:106,name:"RANA ADHIKARY",cat:"NORMAL"},
{sr:107,name:"BIPLOB ROY (AKASH)",cat:"NORMAL"},
{sr:109,name:"PRADEEP MAHATO",cat:"NORMAL"},
{sr:110,name:"RATIKANTA BANERJEE",cat:"NORMAL"},
{sr:111,name:"SOUMYADEEP PAUL (TATAI)",cat:"NORMAL"},
{sr:112,name:"RATAN KUMAR MAHATO",cat:"NORMAL"},
{sr:113,name:"DHANANJAY BAURI (JAGAT)",cat:"NORMAL"},
{sr:114,name:"PRATIK KARMAKAR (DABLA)",cat:"NORMAL"},
{sr:116,name:"RAJU MANDAL",cat:"NORMAL"},
{sr:117,name:"DEBASIS DAN",cat:"NORMAL"},
{sr:118,name:"SUBIR CHOWDHURY",cat:"NORMAL"},
{sr:119,name:"BIKASH BAURI",cat:"NORMAL"},
{sr:120,name:"SARBOJIT HAZRA (BUNTY)",cat:"NORMAL"},
{sr:121,name:"BISWAJIT DUTTA",cat:"NORMAL"},
{sr:122,name:"BIJAY GORAIN",cat:"NORMAL"},
{sr:126,name:"MUBARAK ANSARY",cat:"NORMAL"},
{sr:129,name:"BAPI RAJAK",cat:"NORMAL"},
{sr:131,name:"SOMNATH KARMAKAR (SOMU)",cat:"NORMAL"},
{sr:136,name:"GURUPADA NANDI (BUBAI)",cat:"NORMAL"},
{sr:140,name:"AKASH ROY",cat:"NORMAL"},
{sr:142,name:"BISHAL SAW (BITTU)",cat:"NORMAL"},
{sr:143,name:"ABDUL ANSARY",cat:"NORMAL"},
{sr:144,name:"RAJEN SINGH",cat:"NORMAL"},
{sr:146,name:"SOMNATH RAJAK",cat:"NORMAL"},
{sr:152,name:"SOURAV MUKHERJEE",cat:"NORMAL"},
{sr:154,name:"AJIT BAURI",cat:"NORMAL"},
{sr:157,name:"SIDDHARTH SANKAR MAHANTI",cat:"NORMAL"},
{sr:158,name:"RAHUL DUBEY",cat:"NORMAL"},
{sr:159,name:"JAGANNATH DUTTA",cat:"NORMAL"},
{sr:161,name:"MANOTOSH RAJWAR",cat:"NORMAL"},
{sr:164,name:"GAUTAM KUSHWAHA",cat:"NORMAL"},
{sr:165,name:"BABAN MAHATO",cat:"NORMAL"},
{sr:166,name:"PURNA CH BAGDI",cat:"NORMAL"},
{sr:167,name:"PALLAB BHATTACHARYYA",cat:"NORMAL"},
{sr:170,name:"JITEN GARAI",cat:"NORMAL"},
{sr:171,name:"VISHAL SAH",cat:"NORMAL"},
{sr:173,name:"SUBRATA PARAMANIK",cat:"NORMAL"},
{sr:174,name:"SAIF ALI ANSARI",cat:"NORMAL"},
{sr:176,name:"RAMJAN MAHAMMAD",cat:"NORMAL"},
{sr:179,name:"MALOY PARAMANIK",cat:"NORMAL"},
{sr:180,name:"RIJU RAJAK",cat:"NORMAL"},
{sr:182,name:"CHIRANJIT RAJAK",cat:"NORMAL"},
{sr:184,name:"SK AKBAR",cat:"NORMAL"},
{sr:185,name:"DIPAK CHATTERJEE",cat:"NORMAL"},
{sr:186,name:"ARUP MUKHERJEE",cat:"NORMAL"},
{sr:188,name:"DEBAPRIYA MUKHERJEE (DODON)",cat:"NORMAL"},
{sr:190,name:"ATANU MAHATO",cat:"NORMAL"},
{sr:191,name:"TAPESH CHANDRA PAUL",cat:"NORMAL"},
{sr:192,name:"SACHIN GOPE",cat:"NORMAL"},
{sr:193,name:"RIYAZ SIDDIKI",cat:"NORMAL"},
{sr:196,name:"PRABAL HAZRA",cat:"NORMAL"},
{sr:199,name:"PABAN SAMAL",cat:"NORMAL"},
{sr:200,name:"SIDDHARTHA CHAKRABORTY",cat:"NORMAL"},
{sr:201,name:"MOHIT PRASAD GOPE",cat:"NORMAL"},
{sr:202,name:"RAJKISHOR MAHATO",cat:"NORMAL"},
{sr:203,name:"SUMIT DAS (RIJU)",cat:"NORMAL"},
{sr:204,name:"AKALANKA MAHATO",cat:"NORMAL"},
{sr:206,name:"SULTAN AKHTAR (TIPU)",cat:"NORMAL"},
{sr:208,name:"DEVENDRA CHAKRABORTY",cat:"NORMAL"},
{sr:211,name:"BIKRAM GORAI",cat:"NORMAL"},
{sr:212,name:"BIJOY ROY",cat:"NORMAL"},
{sr:213,name:"JITEN BAURI (MONA)",cat:"NORMAL"},
{sr:215,name:"BAPI MAHATO",cat:"NORMAL"},
{sr:216,name:"BADAL TIWARI",cat:"NORMAL"},
{sr:217,name:"RITESH SINGHA DEB",cat:"NORMAL"},
{sr:218,name:"GANESH MODAK",cat:"NORMAL"},
{sr:219,name:"KARTICK MAHATO",cat:"NORMAL"},
{sr:220,name:"MANAS HARI",cat:"NORMAL"},
{sr:221,name:"AVIJIT ROY",cat:"NORMAL"},
{sr:223,name:"MD IRSAD ANSARI",cat:"NORMAL"},
{sr:225,name:"SUBHASIS BANERJEE",cat:"NORMAL"},
{sr:226,name:"BRAJA KISHORE MAHATO (BEJO)",cat:"NORMAL"},
{sr:227,name:"RABEN SINGH SARDAR",cat:"NORMAL"},
{sr:228,name:"TUSHAR KANTI MAHATO",cat:"NORMAL"},
{sr:229,name:"WASIM KHAN",cat:"NORMAL"},
{sr:230,name:"RAKESH ROY",cat:"NORMAL"},
{sr:231,name:"SUBRATA MAHATO",cat:"NORMAL"},
{sr:232,name:"BIDYUT MAJEE",cat:"NORMAL"},
{sr:234,name:"SK AMJED ALI",cat:"NORMAL"},
{sr:235,name:"BIPUL MAIKAP",cat:"NORMAL"},
{sr:237,name:"SAMIUL ANSARY (CHOTU)",cat:"NORMAL"},
{sr:239,name:"BIKASH SHARMA",cat:"NORMAL"},
{sr:240,name:"AMIT SINGHA",cat:"NORMAL"},
{sr:243,name:"RIVU DAS",cat:"NORMAL"},
{sr:245,name:"DIBYENDU MAHATO",cat:"NORMAL"},
{sr:246,name:"RAHUL RAJAK (BUMBA)",cat:"NORMAL"},
{sr:247,name:"PRAKASH HALWAI",cat:"NORMAL"},
{sr:248,name:"JAYANTA BAURI",cat:"NORMAL"},
{sr:249,name:"SACHIN RAJAK",cat:"NORMAL"},
{sr:250,name:"PARIMAL MAJHI",cat:"NORMAL"},
{sr:252,name:"KIRAN MUKHERJEE (HIRAN)",cat:"NORMAL"},
{sr:254,name:"ARUP BOURI",cat:"NORMAL"},
{sr:255,name:"MILAN BAURI",cat:"NORMAL"},
{sr:256,name:"RAHUL BARAL",cat:"NORMAL"},
{sr:257,name:"BISWAJIT GOPE",cat:"NORMAL"},
{sr:258,name:"SK SATTAR",cat:"NORMAL"},
{sr:260,name:"MAHENDRA BAURI",cat:"NORMAL"},
{sr:262,name:"SHYAMAL BARAN SAHIS",cat:"NORMAL"},
{sr:263,name:"DIPOK GORAI",cat:"NORMAL"},
{sr:265,name:"MANAJ BAURI",cat:"NORMAL"},
{sr:266,name:"DEBABRATA TUDU",cat:"NORMAL"},
{sr:267,name:"SK GOLAM AZHAR",cat:"NORMAL"},
{sr:268,name:"SHYAMAL MANDAL",cat:"NORMAL"},
{sr:273,name:"MD ARMAN",cat:"NORMAL"},
{sr:275,name:"BIBEK BAURI",cat:"NORMAL"},
{sr:276,name:"MD ASLAM",cat:"NORMAL"},
{sr:277,name:"AKASH RAKSHIT",cat:"NORMAL"},
{sr:278,name:"JHULAN MODAK",cat:"NORMAL"},
{sr:279,name:"ARNAB KUNDU",cat:"NORMAL"},
{sr:281,name:"CHANDAN DEY",cat:"NORMAL"},
{sr:282,name:"ABDUL HAMID (ABDUL)",cat:"NORMAL"},
{sr:283,name:"SANDIP MAHATO",cat:"NORMAL"},
{sr:285,name:"SHYAMAL TUDU",cat:"NORMAL"},
{sr:286,name:"SUKANTA MAHATO",cat:"NORMAL"},
{sr:287,name:"SUMAN MAJEE",cat:"NORMAL"},
{sr:289,name:"PRASENJIT SEN (BISHAL)",cat:"NORMAL"},
{sr:291,name:"PARTHA SANTIKARI",cat:"NORMAL"},
{sr:292,name:"PREM KUMAR (SONU)",cat:"NORMAL"},
{sr:293,name:"TABREJ ALAM",cat:"NORMAL"},
{sr:295,name:"SWADESH KUMBHAKAR",cat:"NORMAL"},
{sr:297,name:"SANTOSH KUMAR",cat:"NORMAL"},
{sr:298,name:"BIDHAN MAHATO",cat:"NORMAL"},
{sr:299,name:"DIPAK MUKHERJEE",cat:"NORMAL"},
{sr:301,name:"SK SULTAN",cat:"NORMAL"},
{sr:302,name:"SOUMEN GOPE",cat:"NORMAL"},
{sr:303,name:"SADHAN SHUTRADHAR",cat:"NORMAL"},
{sr:304,name:"PARTHA DEY",cat:"NORMAL"},
{sr:305,name:"SAMIR ORANG",cat:"NORMAL"},
{sr:306,name:"SK JUMMAN (AKHTAR)",cat:"NORMAL"},
{sr:307,name:"AVINANDAN DUTTA",cat:"NORMAL"},
{sr:308,name:"SUDIP RAJAK (CHOTO)",cat:"NORMAL"},
{sr:310,name:"PABAN KALINDI",cat:"NORMAL"},
{sr:311,name:"MAHABIR KUMAR",cat:"NORMAL"},
{sr:312,name:"RAHUL MAHATO",cat:"NORMAL"},
{sr:316,name:"MADAN MAHATO",cat:"NORMAL"},
{sr:317,name:"PREM DHIBAR",cat:"NORMAL"},
{sr:318,name:"MILAN MANDAL",cat:"NORMAL"},
{sr:319,name:"RAVI SHARMA",cat:"NORMAL"},
{sr:321,name:"SUBIR GHOSH",cat:"NORMAL"},
{sr:323,name:"AVIJIT ROY",cat:"NORMAL"},
{sr:324,name:"SOUVIK CHAKRABORTY",cat:"NORMAL"},
{sr:325,name:"SK SADDAM HUSSAIN",cat:"NORMAL"}

];